name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4


      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '8.x'
      - name: Restore backend dependencies
        run: dotnet restore ./TransferRoomInterviewApp/TransferRoomInterviewApp.Server
      - name: Build backend
        run: dotnet build --configuration Release ./TransferRoomInterviewApp/TransferRoomInterviewApp.Server
      - name: Run backend tests
        run: echo "Testing backend here"


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '20'
      - name: Install frontend dependencies
        run: npm install --prefix ./TransferRoomInterviewApp/transferroominterviewapp.client
      - name: Build frontend
        run: npm run build --prefix
      - name: Run frontend tests
        run: echo "Testing frontend here"

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy backend
      run: echo "Deploy backend here"
    - name: Deploy frontend
      run: echo "Deploy frontend here"